### ISSUE TITLE
조회할 과제가 없는 경우 IndexError 발생

### ISSUE THREAD

**Issue by SeonjaeHyeon** [TimeTREE98/MJU-LMS-Crawler#1]
수강과목 중에 과제란에 아직 아무런 과제도 올라오지 않은 경우 다음과 같은 에러가 발생합니다.
```
Traceback (most recent call last):
  File "mju_lms.py", line 55, in <module>
    main()
  File "mju_lms.py", line 48, in main
    Nm = RL.select('td')[1].select('a > div')[0].text
IndexError: list index out of range
````

조회할 과제가 없는 과목의 데이터를 `ReportData`에 넣어 `request` 했을 시의  `response data`는
```html
<table class="bbslist new_bbslist" border="1" summary="과제물 게시판 목록(제목,마감일,지각제출,점수,상태 항목)">
            <caption>게시판 목록</caption>
            <colgroup>
              <col style="width:35px;">
              <col>
              <col style="width:80px;">
              <col style="width:60px;">
              <col style="width:60px;">
              <col style="width:60px;">
              <col style="width:142px;">
            </colgroup>
            <thead>
              <tr>
                
                <th scope="col" class="first">번호</th>
                                
                <th scope="col">제목</th>
                <th scope="col">진행</th>
                <th scope="col">제출</th>
                <th scope="col">점수</th>
                <th scope="col">배점</th>
                <th scope="col" class="last">마감일</th>
              </tr>
            </thead>
            <tbody>
            
            
              <tr>
                <td colspan="7" height="50">조회할 자료가 없습니다</td>
              </tr>
            
            </tbody>
          </table>
```
입니다.

따라서 `Nb`에 `조회할 자료가 없습니다`가 담기므로, 다음과 같이 if문을 추가하면 과제가 없는 과목 데이터를 출력할 때 `Nm`의 `IndexError`를 방지할 수 있겠네요.
```python
for RL in ReportList:
  Nb = RL.select('td')[0].text
  if '없습니다' in Nb:
    print(Nb)
    break
  Nm = RL.select('td')[1].select('a > div')[0].text
  Prg = RL.select('td')[2].text  # 공백 및 개행 제거 처리 필요
  Sub = RL.select('td')[3].select('img')[0]['title']
  print(Nb + ' | ' + Nm + ' | ' + Sub)
```

**Comment by TimeTREE98** [comment]
현재 아이디가 과제가 모두 있는 상황이라, 과제 없는 분 아이디로 테스트 필요!

**Comment by SeonjaeHyeon** [comment]
제가 테스트했을 때는 문제 없이 작동했습니다.
```
글쓰기(KMA02104-5044)
--------- 출석율 -----------
현재출석률 : 47% | 최대출석률 : 100%
--------- 과제 현황 --------
조회할 자료가 없습니다


기초프로그래밍2(HEB01105-5901)
--------- 출석율 -----------
현재출석률 : 0% | 최대출석률 : 100%
--------- 과제 현황 --------
조회할 자료가 없습니다


대중문화와매스컴(KMD02103-5323)
--------- 출석율 -----------
현재출석률 : 38% | 최대출석률 : 100%
--------- 과제 현황 --------
1 | 1주차 출석과제 | 미제출


세계화와사회변화(KMA02113-5170)
--------- 출석율 -----------
현재출석률 : 49% | 최대출석률 : 100%
--------- 과제 현황 --------
1 | 세계화와 사회변화 제1주차 과제 | 미제출


영어4(KMA02124-5194)
--------- 출석율 -----------
현재출석률 : 50% | 최대출석률 : 100%
--------- 과제 현황 --------
1 | 1주차 과제 | 미제출


영어회화4(KMA02126-5209)
--------- 출석율 -----------
현재출석률 : 33.33% | 최대출석률 : 100%
--------- 과제 현황 --------
조회할 자료가 없습니다


인공지능의세계(KMA02138-5941)
--------- 출석율 -----------
현재출석률 : 55.55% | 최대출석률 : 100%
--------- 과제 현황 --------
1 | 인공지능의 세계 1주차 과제 | 제출


채플(KMA02101-5023)
--------- 출석율 -----------
현재출석률 : 50% | 최대출석률 : 100%
--------- 과제 현황 --------
1 | 1주차 채플 과제[1] | 제출


컴퓨터논리의이해(KMI02112-5382)
--------- 출석율 -----------
현재출석률 : 31.5% | 최대출석률 : 100%
--------- 과제 현황 --------
1 | 1주차 과제 | 미제출


```
아마도 제가 듣는 과목 외에 다른 과목들도 문제가 없지 않을까 싶습니다.

**Comment by TimeTREE98** [comment]
소중한 피드백 감사합니다!
